# Generated by Django 3.2.23 on 2023-11-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_alter_filme_data_assistido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
