# Generated by Django 3.2.23 on 2023-11-24 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_alter_filme_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='data_assistido',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='gostaria_assistir',
        ),
        migrations.CreateModel(
            name='FilmeDesejado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gostaria_assistir', models.BooleanField(default=False)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
        migrations.CreateModel(
            name='FilmeAssistido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assistido', models.DateField()),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
    ]
