# Generated by Django 3.2.23 on 2023-11-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0006_auto_20231124_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmedesejado',
            name='filme',
        ),
        migrations.AddField(
            model_name='filme',
            name='data_assistido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='gostaria_assistir',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FilmeAssistido',
        ),
        migrations.DeleteModel(
            name='FilmeDesejado',
        ),
    ]
